using System.Globalization;
using System.Text;
using HarfBuzzSharp;

namespace Adamantium.ShapingOracle;

/// <summary>
/// Writes, for every font of a cases file, its variation axes as HarfBuzz reads them ('A' lines: tag, English name,
/// whether hidden, minimum, default, maximum) and its named instances ('I' lines: English name, design coordinates).
/// </summary>
public static class AxisOracle
{
    private const uint HiddenAxis = 1;

    public static int Write(string casesPath, string fontsRoot, string expectedPath)
    {
        var output = new StringBuilder();
        output.AppendLine($"# HarfBuzzSharp {typeof(Blob).Assembly.GetName().Version}. Generated by Adamantium.ShapingOracle - do not edit.");
        foreach (var line in File.ReadAllLines(casesPath))
        {
            if (line.Length == 0 || line.StartsWith('#'))
            {
                continue;
            }

            Describe(Path.Combine(fontsRoot, line), line, output);
        }

        File.WriteAllText(expectedPath, output.ToString());
        return 0;
    }

    private static void Describe(string fontPath, string name, StringBuilder output)
    {
        using var blob = Blob.FromFile(fontPath);
        using var face = new Face(blob, 0);
        var english = HarfBuzzInterop.LanguageFromString("en", -1);
        var count = 0u;
        var axisCount = HarfBuzzInterop.GetAxisInfos(face.Handle, 0, ref count, null);
        var axes = new HarfBuzzAxisInfo[axisCount];
        count = axisCount;
        HarfBuzzInterop.GetAxisInfos(face.Handle, 0, ref count, axes);
        foreach (var axis in axes)
        {
            output.AppendLine(string.Join("\t", name, "A", Tag(axis.Tag), FeatureOracle.Name(face, axis.NameId, english),
                (axis.Flags & HiddenAxis) != 0 ? "hidden" : "shown", Number(axis.MinValue), Number(axis.DefaultValue),
                Number(axis.MaxValue)));
        }

        var instances = HarfBuzzInterop.GetNamedInstanceCount(face.Handle);
        for (var instance = 0u; instance < instances; instance++)
        {
            var coords = new float[axisCount];
            count = axisCount;
            HarfBuzzInterop.GetNamedInstanceCoords(face.Handle, instance, ref count, coords);
            output.AppendLine(string.Join("\t", name, "I",
                FeatureOracle.Name(face, HarfBuzzInterop.GetNamedInstanceNameId(face.Handle, instance), english),
                string.Join(",", coords.Select(Number))));
        }
    }

    private static string Tag(uint tag) =>
        new([(char)(tag >> 24), (char)((tag >> 16) & 0xFF), (char)((tag >> 8) & 0xFF), (char)(tag & 0xFF)]);

    private static string Number(float value) => value.ToString("0.###", CultureInfo.InvariantCulture);
}
