using System.Globalization;
using System.Text;
using HarfBuzzSharp;

namespace Adamantium.ShapingOracle;

/// <summary>
/// Writes, for every font of a cases file, each glyph with a 'COLR' version 1 paint graph as HarfBuzz paints it, as the
/// steps the engine draws it with: "clip" (glyph and transform), "popclip", "group", "popgroup" (mode) and "fill" (kind,
/// extend, transform, geometry and stops). Transforms are folded into the steps; the clip boxes of 'COLR''s clip list
/// are left out; a group composited with source-over that holds no other composite is dissolved into what is around it,
/// as HarfBuzz wraps every layer in one.
/// </summary>
public static class ColorPaintOracle
{
    private const int SourceOver = 3;
    private const uint Foreground = 0x000000FF;

    private static readonly List<double[]> transforms = [];
    private static readonly List<bool> clips = [];
    private static readonly List<Group> groups = [];

    public static int Write(string casesPath, string fontsRoot, string expectedPath)
    {
        var output = new StringBuilder();
        output.AppendLine($"# HarfBuzzSharp {typeof(Blob).Assembly.GetName().Version}. Generated by Adamantium.ShapingOracle - do not edit.");
        foreach (var line in File.ReadAllLines(casesPath))
        {
            if (line.Length == 0 || line.StartsWith('#'))
            {
                continue;
            }

            Paint(Path.Combine(fontsRoot, line), line, output);
        }

        File.WriteAllText(expectedPath, output.ToString());
        return 0;
    }

    private static void Paint(string fontPath, string name, StringBuilder output)
    {
        using var blob = Blob.FromFile(fontPath);
        using var face = new Face(blob, 0);
        using var font = new HarfBuzzSharp.Font(face);
        font.SetScale(face.UnitsPerEm, face.UnitsPerEm);

        HarfBuzzPaint.PushTransform pushTransform = OnPushTransform;
        HarfBuzzPaint.Pop popTransform = OnPopTransform;
        HarfBuzzPaint.ColorGlyph colorGlyph = OnColorGlyph;
        HarfBuzzPaint.PushClipGlyph pushClipGlyph = OnPushClipGlyph;
        HarfBuzzPaint.PushClipRectangle pushClipRectangle = OnPushClipRectangle;
        HarfBuzzPaint.Pop popClip = OnPopClip;
        HarfBuzzPaint.Color color = OnColor;
        HarfBuzzPaint.LinearGradient linear = OnLinearGradient;
        HarfBuzzPaint.RadialGradient radial = OnRadialGradient;
        HarfBuzzPaint.SweepGradient sweep = OnSweepGradient;
        HarfBuzzPaint.Pop pushGroup = OnPushGroup;
        HarfBuzzPaint.PopGroup popGroup = OnPopGroup;

        var funcs = HarfBuzzPaint.CreateFuncs();
        HarfBuzzPaint.SetPushTransform(funcs, pushTransform, IntPtr.Zero, IntPtr.Zero);
        HarfBuzzPaint.SetPopTransform(funcs, popTransform, IntPtr.Zero, IntPtr.Zero);
        HarfBuzzPaint.SetColorGlyph(funcs, colorGlyph, IntPtr.Zero, IntPtr.Zero);
        HarfBuzzPaint.SetPushClipGlyph(funcs, pushClipGlyph, IntPtr.Zero, IntPtr.Zero);
        HarfBuzzPaint.SetPushClipRectangle(funcs, pushClipRectangle, IntPtr.Zero, IntPtr.Zero);
        HarfBuzzPaint.SetPopClip(funcs, popClip, IntPtr.Zero, IntPtr.Zero);
        HarfBuzzPaint.SetColor(funcs, color, IntPtr.Zero, IntPtr.Zero);
        HarfBuzzPaint.SetLinearGradient(funcs, linear, IntPtr.Zero, IntPtr.Zero);
        HarfBuzzPaint.SetRadialGradient(funcs, radial, IntPtr.Zero, IntPtr.Zero);
        HarfBuzzPaint.SetSweepGradient(funcs, sweep, IntPtr.Zero, IntPtr.Zero);
        HarfBuzzPaint.SetPushGroup(funcs, pushGroup, IntPtr.Zero, IntPtr.Zero);
        HarfBuzzPaint.SetPopGroup(funcs, popGroup, IntPtr.Zero, IntPtr.Zero);

        for (uint glyph = 0; glyph < face.GlyphCount; glyph++)
        {
            if (HarfBuzzPaint.HasPaint(face.Handle, glyph) == 0)
            {
                continue;
            }

            transforms.Clear();
            transforms.Add([1, 0, 0, 1, 0, 0]);
            clips.Clear();
            groups.Clear();
            groups.Add(new Group());
            HarfBuzzPaint.PaintGlyph(font.Handle, glyph, funcs, IntPtr.Zero, 0, Foreground);

            output.Append(name).Append('\t').Append(glyph).Append('\t')
                .AppendLine(string.Join(" | ", groups[0].Steps));
        }

        HarfBuzzPaint.DestroyFuncs(funcs);
        GC.KeepAlive(pushTransform);
        GC.KeepAlive(popTransform);
        GC.KeepAlive(colorGlyph);
        GC.KeepAlive(pushClipGlyph);
        GC.KeepAlive(pushClipRectangle);
        GC.KeepAlive(popClip);
        GC.KeepAlive(color);
        GC.KeepAlive(linear);
        GC.KeepAlive(radial);
        GC.KeepAlive(sweep);
        GC.KeepAlive(pushGroup);
        GC.KeepAlive(popGroup);
    }

    private static void OnPushTransform(IntPtr funcs, IntPtr data, float xx, float yx, float xy, float yy, float dx,
        float dy, IntPtr user)
    {
        var t = transforms[^1];
        transforms.Add(
        [
            xx * t[0] + yx * t[2],
            xx * t[1] + yx * t[3],
            xy * t[0] + yy * t[2],
            xy * t[1] + yy * t[3],
            dx * t[0] + dy * t[2] + t[4],
            dx * t[1] + dy * t[3] + t[5],
        ]);
    }

    private static void OnPopTransform(IntPtr funcs, IntPtr data, IntPtr user)
    {
        transforms.RemoveAt(transforms.Count - 1);
    }

    private static int OnColorGlyph(IntPtr funcs, IntPtr data, uint glyph, IntPtr font, IntPtr user)
    {
        return 0;
    }

    private static void OnPushClipGlyph(IntPtr funcs, IntPtr data, uint glyph, IntPtr font, IntPtr user)
    {
        clips.Add(true);
        var text = new StringBuilder("clip ").Append(glyph);
        Append(text, transforms[^1]);
        groups[^1].Steps.Add(text.ToString());
    }

    private static void OnPushClipRectangle(IntPtr funcs, IntPtr data, float xMin, float yMin, float xMax, float yMax,
        IntPtr user)
    {
        clips.Add(false);
    }

    private static void OnPopClip(IntPtr funcs, IntPtr data, IntPtr user)
    {
        if (clips[^1])
        {
            groups[^1].Steps.Add("popclip");
        }

        clips.RemoveAt(clips.Count - 1);
    }

    private static void OnColor(IntPtr funcs, IntPtr data, int isForeground, uint color, IntPtr user)
    {
        Fill("solid pad", [], [(0, isForeground != 0, color)]);
    }

    private static void OnLinearGradient(IntPtr funcs, IntPtr data, IntPtr colorLine, float x0, float y0, float x1,
        float y1, float x2, float y2, IntPtr user)
    {
        Fill($"linear {Extend(colorLine)}", [x0, y0, x1, y1, x2, y2], Stops(colorLine));
    }

    private static void OnRadialGradient(IntPtr funcs, IntPtr data, IntPtr colorLine, float x0, float y0, float r0,
        float x1, float y1, float r1, IntPtr user)
    {
        Fill($"radial {Extend(colorLine)}", [x0, y0, r0, x1, y1, r1], Stops(colorLine));
    }

    private static void OnSweepGradient(IntPtr funcs, IntPtr data, IntPtr colorLine, float x, float y, float start,
        float end, IntPtr user)
    {
        Fill($"sweep {Extend(colorLine)}", [x, y, start * 180 / Math.PI, end * 180 / Math.PI], Stops(colorLine));
    }

    private static void OnPushGroup(IntPtr funcs, IntPtr data, IntPtr user)
    {
        groups.Add(new Group());
    }

    private static void OnPopGroup(IntPtr funcs, IntPtr data, int mode, IntPtr user)
    {
        var group = groups[^1];
        groups.RemoveAt(groups.Count - 1);
        var parent = groups[^1];
        if (mode == SourceOver && !group.HoldsAComposite)
        {
            parent.Steps.AddRange(group.Steps);
            return;
        }

        parent.Steps.Add("group");
        parent.Steps.AddRange(group.Steps);
        parent.Steps.Add($"popgroup {mode}");
        if (mode != SourceOver)
        {
            parent.HoldsAComposite = true;
        }
    }

    private static void Fill(string head, double[] geometry, (float Offset, bool Foreground, uint Color)[] stops)
    {
        var text = new StringBuilder("fill ").Append(head);
        Append(text, transforms[^1]);
        Append(text, geometry);
        var sorted = stops.OrderBy(s => s.Offset).ToArray();
        text.Append(' ').Append(sorted.Length);
        foreach (var stop in sorted)
        {
            var color = stop.Foreground ? "fg" : $"#{stop.Color >> 8 & 0xFF:x2}{stop.Color >> 16 & 0xFF:x2}{stop.Color >> 24:x2}";
            text.Append(' ').Append(Number(stop.Offset)).Append(' ').Append(color).Append(' ')
                .Append(Number((stop.Color & 0xFF) / 255.0));
        }

        groups[^1].Steps.Add(text.ToString());
    }

    private static (float, bool, uint)[] Stops(IntPtr colorLine)
    {
        uint count = 0;
        var total = HarfBuzzPaint.GetColorStops(colorLine, 0, ref count, null);
        var stops = new HarfBuzzColorStop[total];
        count = total;
        HarfBuzzPaint.GetColorStops(colorLine, 0, ref count, stops);
        return stops.Select(s => (s.Offset, s.IsForeground != 0, s.Color)).ToArray();
    }

    private static string Extend(IntPtr colorLine) =>
        HarfBuzzPaint.GetExtend(colorLine) switch
        {
            1 => "repeat",
            2 => "reflect",
            _ => "pad",
        };

    private static void Append(StringBuilder text, double[] values)
    {
        foreach (var value in values)
        {
            text.Append(' ').Append(Number(value));
        }
    }

    private static string Number(double value) => Math.Round(value, 4).ToString("0.####", CultureInfo.InvariantCulture);

    private sealed class Group
    {
        public List<string> Steps { get; } = [];

        public bool HoldsAComposite { get; set; }
    }
}
