using System.Runtime.InteropServices;
using System.Text;
using HarfBuzzSharp;

namespace Adamantium.ShapingOracle;

/// <summary>
/// Writes, for every font and size of a cases file, each glyph with a color image ('CBDT' or 'sbix') as HarfBuzz finds
/// it at that size: the PNG's length and FNV-1a hash, and the glyph's extents in font units (x and y bearing, width,
/// height).
/// </summary>
public static class ColorBitmapOracle
{
    public static int Write(string casesPath, string fontsRoot, string expectedPath)
    {
        var output = new StringBuilder();
        output.AppendLine($"# HarfBuzzSharp {typeof(Blob).Assembly.GetName().Version}. Generated by Adamantium.ShapingOracle - do not edit.");
        foreach (var line in File.ReadAllLines(casesPath))
        {
            if (line.Length == 0 || line.StartsWith('#'))
            {
                continue;
            }

            var fields = line.Split('\t');
            Describe(Path.Combine(fontsRoot, fields[0]), int.Parse(fields[1]), line, output);
        }

        File.WriteAllText(expectedPath, output.ToString());
        return 0;
    }

    private static void Describe(string fontPath, int pixelsPerEm, string name, StringBuilder output)
    {
        using var blob = Blob.FromFile(fontPath);
        using var face = new Face(blob, 0);
        using var font = new HarfBuzzSharp.Font(face);
        font.SetScale(face.UnitsPerEm, face.UnitsPerEm);
        HarfBuzzInterop.SetPixelsPerEm(font.Handle, (uint)pixelsPerEm, (uint)pixelsPerEm);
        output.Append(name);
        for (uint glyph = 0; glyph < face.GlyphCount; glyph++)
        {
            var png = HarfBuzzInterop.ReferencePng(font.Handle, glyph);
            var length = HarfBuzzInterop.GetBlobLength(png);
            if (length > 0)
            {
                var data = new byte[length];
                Marshal.Copy(HarfBuzzInterop.GetBlobData(png, out _), data, 0, (int)length);
                font.TryGetGlyphExtents(glyph, out var extents);
                output.Append($"\t{glyph}={length}:{Hash(data):x8}:{extents.XBearing},{extents.YBearing},{extents.Width},{extents.Height}");
            }

            HarfBuzzInterop.DestroyBlob(png);
        }

        output.AppendLine();
    }

    /// <summary>FNV-1a, 32 bits.</summary>
    public static uint Hash(byte[] data)
    {
        var hash = 2166136261u;
        foreach (var b in data)
        {
            hash = (hash ^ b) * 16777619u;
        }

        return hash;
    }
}
