using System.Globalization;
using System.Text;
using HarfBuzzSharp;

namespace Adamantium.ShapingOracle;

/// <summary>
/// Writes, for every font of a cases file, each glyph with a 'COLR' version 1 paint graph as HarfBuzz paints it,
/// flattened into layers: the clipping glyph and its transform, then the fill, its transform and its stops. A source
/// composited onto a solid backdrop with SrcIn keeps the backdrop's alpha; every other composite draws over. Those are
/// the engine's own simplifications, so composites are checked against them, not against how HarfBuzz composites.
/// </summary>
public static class ColorPaintOracle
{
    private const int SourceIn = 5;
    private const uint Foreground = 0x000000FF;

    private static readonly List<double[]> transforms = [];
    private static readonly List<(uint? Glyph, double[] Transform)> clips = [];
    private static readonly List<List<Item>> groups = [];

    public static int Write(string casesPath, string fontsRoot, string expectedPath)
    {
        var output = new StringBuilder();
        output.AppendLine($"# HarfBuzzSharp {typeof(Blob).Assembly.GetName().Version}. Generated by Adamantium.ShapingOracle - do not edit.");
        foreach (var line in File.ReadAllLines(casesPath))
        {
            if (line.Length == 0 || line.StartsWith('#'))
            {
                continue;
            }

            Paint(Path.Combine(fontsRoot, line), line, output);
        }

        File.WriteAllText(expectedPath, output.ToString());
        return 0;
    }

    private static void Paint(string fontPath, string name, StringBuilder output)
    {
        using var blob = Blob.FromFile(fontPath);
        using var face = new Face(blob, 0);
        using var font = new HarfBuzzSharp.Font(face);
        font.SetScale(face.UnitsPerEm, face.UnitsPerEm);

        HarfBuzzPaint.PushTransform pushTransform = OnPushTransform;
        HarfBuzzPaint.Pop popTransform = OnPopTransform;
        HarfBuzzPaint.ColorGlyph colorGlyph = OnColorGlyph;
        HarfBuzzPaint.PushClipGlyph pushClipGlyph = OnPushClipGlyph;
        HarfBuzzPaint.PushClipRectangle pushClipRectangle = OnPushClipRectangle;
        HarfBuzzPaint.Pop popClip = OnPopClip;
        HarfBuzzPaint.Color color = OnColor;
        HarfBuzzPaint.LinearGradient linear = OnLinearGradient;
        HarfBuzzPaint.RadialGradient radial = OnRadialGradient;
        HarfBuzzPaint.SweepGradient sweep = OnSweepGradient;
        HarfBuzzPaint.Pop pushGroup = OnPushGroup;
        HarfBuzzPaint.PopGroup popGroup = OnPopGroup;

        var funcs = HarfBuzzPaint.CreateFuncs();
        HarfBuzzPaint.SetPushTransform(funcs, pushTransform, IntPtr.Zero, IntPtr.Zero);
        HarfBuzzPaint.SetPopTransform(funcs, popTransform, IntPtr.Zero, IntPtr.Zero);
        HarfBuzzPaint.SetColorGlyph(funcs, colorGlyph, IntPtr.Zero, IntPtr.Zero);
        HarfBuzzPaint.SetPushClipGlyph(funcs, pushClipGlyph, IntPtr.Zero, IntPtr.Zero);
        HarfBuzzPaint.SetPushClipRectangle(funcs, pushClipRectangle, IntPtr.Zero, IntPtr.Zero);
        HarfBuzzPaint.SetPopClip(funcs, popClip, IntPtr.Zero, IntPtr.Zero);
        HarfBuzzPaint.SetColor(funcs, color, IntPtr.Zero, IntPtr.Zero);
        HarfBuzzPaint.SetLinearGradient(funcs, linear, IntPtr.Zero, IntPtr.Zero);
        HarfBuzzPaint.SetRadialGradient(funcs, radial, IntPtr.Zero, IntPtr.Zero);
        HarfBuzzPaint.SetSweepGradient(funcs, sweep, IntPtr.Zero, IntPtr.Zero);
        HarfBuzzPaint.SetPushGroup(funcs, pushGroup, IntPtr.Zero, IntPtr.Zero);
        HarfBuzzPaint.SetPopGroup(funcs, popGroup, IntPtr.Zero, IntPtr.Zero);

        for (uint glyph = 0; glyph < face.GlyphCount; glyph++)
        {
            if (HarfBuzzPaint.HasPaint(face.Handle, glyph) == 0)
            {
                continue;
            }

            transforms.Clear();
            transforms.Add([1, 0, 0, 1, 0, 0]);
            clips.Clear();
            groups.Clear();
            groups.Add([]);
            HarfBuzzPaint.PaintGlyph(font.Handle, glyph, funcs, IntPtr.Zero, 0, Foreground);

            var layers = groups[0].Where(i => i.Glyph != null).Select(i => i.Text);
            output.Append(name).Append('\t').Append(glyph).Append('\t').AppendLine(string.Join(" | ", layers));
        }

        HarfBuzzPaint.DestroyFuncs(funcs);
        GC.KeepAlive(pushTransform);
        GC.KeepAlive(popTransform);
        GC.KeepAlive(colorGlyph);
        GC.KeepAlive(pushClipGlyph);
        GC.KeepAlive(pushClipRectangle);
        GC.KeepAlive(popClip);
        GC.KeepAlive(color);
        GC.KeepAlive(linear);
        GC.KeepAlive(radial);
        GC.KeepAlive(sweep);
        GC.KeepAlive(pushGroup);
        GC.KeepAlive(popGroup);
    }

    private static void OnPushTransform(IntPtr funcs, IntPtr data, float xx, float yx, float xy, float yy, float dx,
        float dy, IntPtr user)
    {
        var t = transforms[^1];
        transforms.Add(
        [
            xx * t[0] + yx * t[2],
            xx * t[1] + yx * t[3],
            xy * t[0] + yy * t[2],
            xy * t[1] + yy * t[3],
            dx * t[0] + dy * t[2] + t[4],
            dx * t[1] + dy * t[3] + t[5],
        ]);
    }

    private static void OnPopTransform(IntPtr funcs, IntPtr data, IntPtr user)
    {
        transforms.RemoveAt(transforms.Count - 1);
    }

    private static int OnColorGlyph(IntPtr funcs, IntPtr data, uint glyph, IntPtr font, IntPtr user)
    {
        return 0;
    }

    private static void OnPushClipGlyph(IntPtr funcs, IntPtr data, uint glyph, IntPtr font, IntPtr user)
    {
        clips.Add((glyph, transforms[^1]));
    }

    private static void OnPushClipRectangle(IntPtr funcs, IntPtr data, float xMin, float yMin, float xMax, float yMax,
        IntPtr user)
    {
        clips.Add((null, transforms[^1]));
    }

    private static void OnPopClip(IntPtr funcs, IntPtr data, IntPtr user)
    {
        clips.RemoveAt(clips.Count - 1);
    }

    private static void OnColor(IntPtr funcs, IntPtr data, int isForeground, uint color, IntPtr user)
    {
        Fill("solid pad", [], [(0, isForeground != 0, color)]);
    }

    private static void OnLinearGradient(IntPtr funcs, IntPtr data, IntPtr colorLine, float x0, float y0, float x1,
        float y1, float x2, float y2, IntPtr user)
    {
        Fill($"linear {Extend(colorLine)}", [x0, y0, x1, y1, x2, y2], Stops(colorLine));
    }

    private static void OnRadialGradient(IntPtr funcs, IntPtr data, IntPtr colorLine, float x0, float y0, float r0,
        float x1, float y1, float r1, IntPtr user)
    {
        Fill($"radial {Extend(colorLine)}", [x0, y0, r0, x1, y1, r1], Stops(colorLine));
    }

    private static void OnSweepGradient(IntPtr funcs, IntPtr data, IntPtr colorLine, float x, float y, float start,
        float end, IntPtr user)
    {
        Fill($"sweep {Extend(colorLine)}", [x, y, start * 180 / Math.PI, end * 180 / Math.PI], Stops(colorLine));
    }

    private static void OnPushGroup(IntPtr funcs, IntPtr data, IntPtr user)
    {
        groups.Add([]);
    }

    private static void OnPopGroup(IntPtr funcs, IntPtr data, int mode, IntPtr user)
    {
        var source = groups[^1];
        groups.RemoveAt(groups.Count - 1);
        var backdrop = groups[^1];
        if (mode != SourceIn)
        {
            backdrop.AddRange(source);
            return;
        }

        var opacity = backdrop.Count == 1 && backdrop[0].Glyph == null ? backdrop[0].Alpha : 1;
        backdrop.Clear();
        backdrop.AddRange(source.Select(i => i.WithOpacity(opacity)));
    }

    private static void Fill(string head, double[] geometry, (float Offset, bool Foreground, uint Color)[] stops)
    {
        var clip = clips.LastOrDefault(c => c.Glyph != null);
        if (clip.Glyph == null)
        {
            var alpha = head.StartsWith("solid") ? (stops[0].Color & 0xFF) / 255.0 : 1;
            groups[^1].Add(new Item(null, alpha, null, 1));
            return;
        }

        var text = new StringBuilder();
        text.Append(clip.Glyph.Value);
        Append(text, clip.Transform);
        text.Append(' ').Append(head);
        Append(text, transforms[^1]);
        Append(text, geometry);
        groups[^1].Add(new Item(clip.Glyph, 1, (text.ToString(), stops.OrderBy(s => s.Offset).ToArray()), 1));
    }

    private static (float, bool, uint)[] Stops(IntPtr colorLine)
    {
        uint count = 0;
        var total = HarfBuzzPaint.GetColorStops(colorLine, 0, ref count, null);
        var stops = new HarfBuzzColorStop[total];
        count = total;
        HarfBuzzPaint.GetColorStops(colorLine, 0, ref count, stops);
        return stops.Select(s => (s.Offset, s.IsForeground != 0, s.Color)).ToArray();
    }

    private static string Extend(IntPtr colorLine) =>
        HarfBuzzPaint.GetExtend(colorLine) switch
        {
            1 => "repeat",
            2 => "reflect",
            _ => "pad",
        };

    private static void Append(StringBuilder text, double[] values)
    {
        foreach (var value in values)
        {
            text.Append(' ').Append(Number(value));
        }
    }

    private static string Number(double value) => Math.Round(value, 4).ToString("0.####", CultureInfo.InvariantCulture);

    private sealed record Item(uint? Glyph, double Alpha, (string Head, (float Offset, bool Foreground, uint Color)[] Stops)? Fill,
        double Opacity)
    {
        public Item WithOpacity(double opacity) => this with { Opacity = Opacity * opacity };

        public string Text
        {
            get
            {
                var text = new StringBuilder(Fill.Value.Head);
                text.Append(' ').Append(Fill.Value.Stops.Length);
                foreach (var stop in Fill.Value.Stops)
                {
                    var color = stop.Foreground ? "fg" : $"#{stop.Color >> 8 & 0xFF:x2}{stop.Color >> 16 & 0xFF:x2}{stop.Color >> 24:x2}";
                    text.Append(' ').Append(Number(stop.Offset)).Append(' ').Append(color).Append(' ')
                        .Append(Number((stop.Color & 0xFF) / 255.0 * Opacity));
                }

                return text.ToString();
            }
        }
    }
}
