using System.Text;
using HarfBuzzSharp;

namespace Adamantium.ShapingOracle;

/// <summary>
/// Writes, for every font of a cases file, its 'GSUB' features as HarfBuzz reads them: each feature's 'name' IDs with
/// their English strings, its named parameters and the characters it varies ('F' lines), and every glyph a single or
/// alternate substitution of each of its lookups turns a glyph into ('A' lines).
/// </summary>
public static class FeatureOracle
{
    private const uint Gsub = 0x47535542;

    public static int Write(string casesPath, string fontsRoot, string expectedPath)
    {
        var output = new StringBuilder();
        output.AppendLine($"# HarfBuzzSharp {typeof(Blob).Assembly.GetName().Version}. Generated by Adamantium.ShapingOracle - do not edit.");
        foreach (var line in File.ReadAllLines(casesPath))
        {
            if (line.Length == 0 || line.StartsWith('#'))
            {
                continue;
            }

            Describe(Path.Combine(fontsRoot, line), line, output);
        }

        File.WriteAllText(expectedPath, output.ToString());
        return 0;
    }

    private static void Describe(string fontPath, string name, StringBuilder output)
    {
        using var blob = Blob.FromFile(fontPath);
        using var face = new Face(blob, 0);
        var english = HarfBuzzInterop.LanguageFromString("en", -1);
        var count = 0u;
        var featureCount = HarfBuzzInterop.GetFeatureTags(face.Handle, Gsub, 0, ref count, null);
        var tags = new uint[featureCount];
        count = featureCount;
        HarfBuzzInterop.GetFeatureTags(face.Handle, Gsub, 0, ref count, tags);
        for (var feature = 0u; feature < featureCount; feature++)
        {
            var tag = Tag(tags[feature]);
            output.Append($"{name}\tF\t{tag}");
            if (HarfBuzzInterop.GetFeatureNameIds(face.Handle, Gsub, feature, out var label, out var tooltip, out var sample,
                    out var parameterCount, out var firstParameter))
            {
                var parameters = Enumerable.Range(0, (int)parameterCount)
                    .Select(i => Escape(Name(face, firstParameter + (uint)i, english)));
                output.Append($"\t{Escape(Name(face, label, english))}\t{Escape(Name(face, tooltip, english))}")
                    .Append($"\t{Escape(Name(face, sample, english))}\t{string.Join(";", parameters)}")
                    .Append($"\t{string.Join(",", Characters(face, feature).Select(c => c.ToString("X4")))}");
            }

            output.AppendLine();
            foreach (var lookup in Lookups(face, feature))
            {
                for (var glyph = 0u; glyph < face.GlyphCount; glyph++)
                {
                    var alternates = Alternates(face, lookup, glyph);
                    if (alternates.Length > 0)
                    {
                        output.AppendLine($"{name}\tA\t{tag}\t{lookup}\t{glyph}\t{string.Join(",", alternates)}");
                    }
                }
            }
        }
    }

    internal static string Name(Face face, uint nameId, IntPtr language)
    {
        if (nameId == 0xFFFF || nameId == 0)
        {
            return "";
        }

        var size = 0u;
        var length = HarfBuzzInterop.GetName(face.Handle, nameId, language, ref size, null);
        if (length == 0)
        {
            return "";
        }

        var text = new byte[length + 1];
        size = length + 1;
        HarfBuzzInterop.GetName(face.Handle, nameId, language, ref size, text);
        return Encoding.UTF8.GetString(text, 0, (int)length);
    }

    private static uint[] Characters(Face face, uint feature)
    {
        var count = 0u;
        var total = HarfBuzzInterop.GetFeatureCharacters(face.Handle, Gsub, feature, 0, ref count, null);
        var characters = new uint[total];
        count = total;
        HarfBuzzInterop.GetFeatureCharacters(face.Handle, Gsub, feature, 0, ref count, characters);
        return characters;
    }

    private static uint[] Lookups(Face face, uint feature)
    {
        var count = 0u;
        var total = HarfBuzzInterop.GetFeatureLookups(face.Handle, Gsub, feature, 0, ref count, null);
        var lookups = new uint[total];
        count = total;
        HarfBuzzInterop.GetFeatureLookups(face.Handle, Gsub, feature, 0, ref count, lookups);
        return lookups;
    }

    private static uint[] Alternates(Face face, uint lookup, uint glyph)
    {
        var count = 0u;
        var total = HarfBuzzInterop.GetGlyphAlternates(face.Handle, lookup, glyph, 0, ref count, null);
        if (total == 0)
        {
            return [];
        }

        var alternates = new uint[total];
        count = total;
        HarfBuzzInterop.GetGlyphAlternates(face.Handle, lookup, glyph, 0, ref count, alternates);
        return alternates;
    }

    private static string Tag(uint tag) =>
        new([(char)(tag >> 24), (char)((tag >> 16) & 0xFF), (char)((tag >> 8) & 0xFF), (char)(tag & 0xFF)]);

    private static string Escape(string text) =>
        text.Replace("\\", "\\\\").Replace("\t", "\\t").Replace("\n", "\\n").Replace("\r", "\\r").Replace(";", "\\;");
}
