using System.Globalization;
using System.Text;
using HarfBuzzSharp;

namespace Adamantium.ShapingOracle;

/// <summary>
/// Writes, for every case of a cases file (font, axis values), the font-wide metrics HarfBuzz gives at those axis values
/// in font units, 'MVAR' deltas applied: line ascender, descender and gap, cap height, underline and strikeout.
/// </summary>
public static class MetricsOracle
{
    private static readonly string[] Tags = ["hasc", "hdsc", "hlgp", "cpht", "undo", "unds", "stro", "strs"];

    public static int Write(string casesPath, string fontsRoot, string expectedPath)
    {
        var output = new StringBuilder();
        output.AppendLine($"# HarfBuzzSharp {typeof(Blob).Assembly.GetName().Version}. Generated by Adamantium.ShapingOracle - do not edit.");
        foreach (var line in File.ReadAllLines(casesPath))
        {
            if (line.Length == 0 || line.StartsWith('#'))
            {
                continue;
            }

            var fields = line.Split('\t');
            output.Append(line).Append('\t').AppendLine(Measure(Path.Combine(fontsRoot, fields[0]), fields[1]));
        }

        File.WriteAllText(expectedPath, output.ToString());
        return 0;
    }

    private static string Measure(string fontPath, string variations)
    {
        using var blob = Blob.FromFile(fontPath);
        using var face = new Face(blob, 0);
        using var font = new HarfBuzzSharp.Font(face);
        var settings = variations.Split(',', StringSplitOptions.RemoveEmptyEntries)
            .Select(v => v.Split('='))
            .Select(v => new HarfBuzzVariation(Tag(v[0].Trim()), float.Parse(v[1], CultureInfo.InvariantCulture)))
            .ToArray();
        HarfBuzzInterop.SetVariations(font.Handle, settings, (uint)settings.Length);

        return string.Join(" ", Tags.Select(tag =>
            HarfBuzzInterop.GetMetric(font.Handle, Tag(tag), out var position)
                ? string.Create(CultureInfo.InvariantCulture, $"{tag}={position}")
                : $"{tag}=-"));
    }

    private static uint Tag(string tag) =>
        (uint)tag[0] << 24 | (uint)tag[1] << 16 | (uint)tag[2] << 8 | tag[3];
}
