using System.Globalization;
using System.Text;
using HarfBuzzSharp;
using Buffer = HarfBuzzSharp.Buffer;

namespace Adamantium.ShapingOracle;

/// <summary>
/// Shapes every case of a cases file with HarfBuzz and writes the expected results the font tests compare against.
/// Usage: Adamantium.ShapingOracle &lt;cases.txt&gt; &lt;fonts root&gt; &lt;expected.txt&gt;; with "variations" first,
/// writes each glyph's advance and extents at the axis values of each case instead; with "paint" first, each color
/// glyph's flattened paint graph; with "bitmaps" first, each color image's PNG and extents at the size of each case;
/// with "features" first, each font's 'GSUB' feature names and glyph alternates; with "axes" first, each font's
/// variation axes and named instances; with "metrics" first, the font-wide metrics at the axis values of each case.
/// </summary>
public static class Program
{
    public static int Main(string[] args)
    {
        if (args.Length == 4 && args[0] == "variations")
        {
            return VariationOracle.Write(args[1], args[2], args[3]);
        }

        if (args.Length == 4 && args[0] == "paint")
        {
            return ColorPaintOracle.Write(args[1], args[2], args[3]);
        }

        if (args.Length == 4 && args[0] == "bitmaps")
        {
            return ColorBitmapOracle.Write(args[1], args[2], args[3]);
        }

        if (args.Length == 4 && args[0] == "features")
        {
            return FeatureOracle.Write(args[1], args[2], args[3]);
        }

        if (args.Length == 4 && args[0] == "axes")
        {
            return AxisOracle.Write(args[1], args[2], args[3]);
        }

        if (args.Length == 4 && args[0] == "metrics")
        {
            return MetricsOracle.Write(args[1], args[2], args[3]);
        }

        if (args.Length == 4 && args[0] == "shapevar")
        {
            return ShapeVaried(args[1], args[2], args[3]);
        }

        if (args.Length != 3)
        {
            Console.Error.WriteLine("Usage: Adamantium.ShapingOracle [variations|paint|bitmaps|features|axes|metrics] <cases.txt> <fonts root> <expected.txt>");
            return 1;
        }

        var output = new StringBuilder();
        output.AppendLine($"# HarfBuzzSharp {typeof(Blob).Assembly.GetName().Version}. Generated by Adamantium.ShapingOracle - do not edit.");
        foreach (var line in File.ReadAllLines(args[0]))
        {
            if (line.Length == 0 || line.StartsWith('#'))
            {
                continue;
            }

            var fields = line.Split('\t');
            var result = Shape(Path.Combine(args[1], fields[0]), fields[1], fields[2], fields[3], Unescape(fields[4]));
            output.Append(line).Append('\t').AppendLine(result);
        }

        File.WriteAllText(args[2], output.ToString());
        return 0;
    }

    // Cases of font, script, language, features, axis values and text: shaped at those axis values.
    private static int ShapeVaried(string casesPath, string fontsRoot, string expectedPath)
    {
        var output = new StringBuilder();
        output.AppendLine($"# HarfBuzzSharp {typeof(Blob).Assembly.GetName().Version}. Generated by Adamantium.ShapingOracle - do not edit.");
        foreach (var line in File.ReadAllLines(casesPath))
        {
            if (line.Length == 0 || line.StartsWith('#'))
            {
                continue;
            }

            var fields = line.Split('\t');
            var result = Shape(Path.Combine(fontsRoot, fields[0]), fields[1], fields[2], fields[3], Unescape(fields[5]),
                fields[4]);
            output.Append(line).Append('\t').AppendLine(result);
        }

        File.WriteAllText(expectedPath, output.ToString());
        return 0;
    }

    private static string Shape(string fontPath, string script, string language, string features, string text,
        string variations = "")
    {
        using var blob = Blob.FromFile(fontPath);
        using var face = new Face(blob, 0);
        using var font = new HarfBuzzSharp.Font(face);
        var settings = variations.Split(',', StringSplitOptions.RemoveEmptyEntries)
            .Select(v => v.Split('='))
            .Select(v => new HarfBuzzVariation(Tag(v[0].Trim()), float.Parse(v[1], CultureInfo.InvariantCulture)))
            .ToArray();
        HarfBuzzInterop.SetVariations(font.Handle, settings, (uint)settings.Length);
        using var buffer = new Buffer();

        buffer.AddUtf16(text);
        buffer.Script = Script.Parse(script);
        buffer.Direction = buffer.Script.HorizontalDirection == Direction.RightToLeft
            ? Direction.RightToLeft
            : Direction.LeftToRight;
        if (language.Length > 0)
        {
            buffer.Language = new Language(language);
        }

        var parsed = features.Length == 0
            ? []
            : features.Split(',').Select(f => Feature.Parse(f.Trim())).ToArray();
        font.Shape(buffer, parsed);

        var infos = buffer.GlyphInfos;
        var positions = buffer.GlyphPositions;
        var glyphs = new List<string>();
        for (var i = 0; i < infos.Length; i++)
        {
            glyphs.Add(Format(infos[i], positions[i]));
        }

        return string.Join(' ', glyphs);
    }

    private static uint Tag(string tag) =>
        (uint)tag[0] << 24 | (uint)tag[1] << 16 | (uint)tag[2] << 8 | tag[3];

    private static string Format(GlyphInfo info, GlyphPosition position)
    {
        var text = new StringBuilder();
        text.Append(info.Codepoint.ToString(CultureInfo.InvariantCulture)).Append('=').Append(info.Cluster);
        if (position.XOffset != 0 || position.YOffset != 0)
        {
            text.Append('@').Append(position.XOffset).Append(',').Append(position.YOffset);
        }

        text.Append('+').Append(position.XAdvance);
        return text.ToString();
    }

    private static string Unescape(string text)
    {
        var result = new StringBuilder();
        for (var i = 0; i < text.Length; i++)
        {
            if (text[i] == '{' && text.AsSpan(i).StartsWith("{U+"))
            {
                var close = text.IndexOf('}', i);
                var code = int.Parse(text.AsSpan(i + 3, close - i - 3), NumberStyles.HexNumber);
                result.Append(char.ConvertFromUtf32(code));
                i = close;
                continue;
            }

            result.Append(text[i]);
        }

        return result.ToString();
    }
}
