using System.Globalization;
using System.Text;
using HarfBuzzSharp;
using Buffer = HarfBuzzSharp.Buffer;

namespace Adamantium.ShapingOracle;

/// <summary>
/// Shapes every case of a cases file with HarfBuzz and writes the expected results the font tests compare against.
/// Usage: Adamantium.ShapingOracle &lt;cases.txt&gt; &lt;fonts root&gt; &lt;expected.txt&gt;
/// </summary>
public static class Program
{
    public static int Main(string[] args)
    {
        if (args.Length != 3)
        {
            Console.Error.WriteLine("Usage: Adamantium.ShapingOracle <cases.txt> <fonts root> <expected.txt>");
            return 1;
        }

        var output = new StringBuilder();
        output.AppendLine($"# HarfBuzzSharp {typeof(Blob).Assembly.GetName().Version}. Generated by Adamantium.ShapingOracle - do not edit.");
        foreach (var line in File.ReadAllLines(args[0]))
        {
            if (line.Length == 0 || line.StartsWith('#'))
            {
                continue;
            }

            var fields = line.Split('\t');
            var result = Shape(Path.Combine(args[1], fields[0]), fields[1], fields[2], fields[3], Unescape(fields[4]));
            output.Append(line).Append('\t').AppendLine(result);
        }

        File.WriteAllText(args[2], output.ToString());
        return 0;
    }

    private static string Shape(string fontPath, string script, string language, string features, string text)
    {
        using var blob = Blob.FromFile(fontPath);
        using var face = new Face(blob, 0);
        using var font = new HarfBuzzSharp.Font(face);
        using var buffer = new Buffer();

        buffer.AddUtf16(text);
        buffer.Direction = Direction.LeftToRight;
        buffer.Script = Script.Parse(script);
        if (language.Length > 0)
        {
            buffer.Language = new Language(language);
        }

        var parsed = features.Length == 0
            ? []
            : features.Split(',').Select(f => Feature.Parse(f.Trim())).ToArray();
        font.Shape(buffer, parsed);

        var infos = buffer.GlyphInfos;
        var positions = buffer.GlyphPositions;
        var glyphs = new List<string>();
        for (var i = 0; i < infos.Length; i++)
        {
            glyphs.Add(Format(infos[i], positions[i]));
        }

        return string.Join(' ', glyphs);
    }

    private static string Format(GlyphInfo info, GlyphPosition position)
    {
        var text = new StringBuilder();
        text.Append(info.Codepoint.ToString(CultureInfo.InvariantCulture)).Append('=').Append(info.Cluster);
        if (position.XOffset != 0 || position.YOffset != 0)
        {
            text.Append('@').Append(position.XOffset).Append(',').Append(position.YOffset);
        }

        text.Append('+').Append(position.XAdvance);
        return text.ToString();
    }

    private static string Unescape(string text)
    {
        var result = new StringBuilder();
        for (var i = 0; i < text.Length; i++)
        {
            if (text[i] == '{' && text.AsSpan(i).StartsWith("{U+"))
            {
                var close = text.IndexOf('}', i);
                var code = int.Parse(text.AsSpan(i + 3, close - i - 3), NumberStyles.HexNumber);
                result.Append(char.ConvertFromUtf32(code));
                i = close;
                continue;
            }

            result.Append(text[i]);
        }

        return result.ToString();
    }
}
