using System.Globalization;
using System.Text;
using HarfBuzzSharp;

namespace Adamantium.ShapingOracle;

/// <summary>
/// Writes, for every case of a cases file (font, axis values), each glyph's advance and extents in font units as
/// HarfBuzz computes them at those axis values: "glyph:advance:xMin,yMin,xMax,yMax".
/// </summary>
public static class VariationOracle
{
    public static int Write(string casesPath, string fontsRoot, string expectedPath)
    {
        var output = new StringBuilder();
        output.AppendLine($"# HarfBuzzSharp {typeof(Blob).Assembly.GetName().Version}. Generated by Adamantium.ShapingOracle - do not edit.");
        foreach (var line in File.ReadAllLines(casesPath))
        {
            if (line.Length == 0 || line.StartsWith('#'))
            {
                continue;
            }

            var fields = line.Split('\t');
            output.Append(line).Append('\t').AppendLine(Measure(Path.Combine(fontsRoot, fields[0]), fields[1]));
        }

        File.WriteAllText(expectedPath, output.ToString());
        return 0;
    }

    private static string Measure(string fontPath, string variations)
    {
        using var blob = Blob.FromFile(fontPath);
        using var face = new Face(blob, 0);
        using var font = new HarfBuzzSharp.Font(face);
        var settings = variations.Split(',', StringSplitOptions.RemoveEmptyEntries)
            .Select(v => v.Split('='))
            .Select(v => new HarfBuzzVariation(Tag(v[0].Trim()), float.Parse(v[1], CultureInfo.InvariantCulture)))
            .ToArray();
        HarfBuzzInterop.SetVariations(font.Handle, settings, (uint)settings.Length);

        var glyphs = new List<string>();
        for (uint glyph = 0; glyph < face.GlyphCount; glyph++)
        {
            var advance = font.GetHorizontalGlyphAdvance(glyph);
            font.TryGetGlyphExtents(glyph, out var extents);
            glyphs.Add(string.Create(CultureInfo.InvariantCulture,
                $"{glyph}:{advance}:{extents.XBearing},{extents.YBearing + extents.Height},{extents.XBearing + extents.Width},{extents.YBearing}"));
        }

        return string.Join(' ', glyphs);
    }

    private static uint Tag(string tag) =>
        (uint)tag[0] << 24 | (uint)tag[1] << 16 | (uint)tag[2] << 8 | tag[3];
}
