// Hyphenates every word of a words file with the hyphen package and writes the expected results the font tests
// compare against. Usage: npm install && npm run oracle
const fs = require("fs");
const createHyphenator = require("hyphen/hyphen.js");

const mark = "|";

// Language tag -> the package's pattern file, and the letters a word keeps at each side of a break by the hyphenmins
// of the hyph-utf8 file (the package itself keeps one).
const languages = {
  ru: { file: "ru", left: 2, right: 2 },
  en: { file: "en-us", left: 2, right: 3 },
  "en-GB": { file: "en-gb", left: 2, right: 3 },
  de: { file: "de-1996", left: 2, right: 2 },
  fr: { file: "fr", left: 2, right: 2 },
  es: { file: "es", left: 2, right: 2 },
};

const [wordsPath, expectedPath] = process.argv.slice(2);
const hyphenators = {};
let output = "# hyphen 1.14.1. Generated by Tests/Adamantium.HyphenationOracle - do not edit.\n";
for (const line of fs.readFileSync(wordsPath, "utf8").split(/\r?\n/)) {
  if (!line || line.startsWith("#")) {
    continue;
  }

  const [language, word] = line.split("\t");
  const { file, left, right } = languages[language];
  hyphenators[language] ??= createHyphenator(require(`hyphen/patterns/${file}.js`), {
    hyphenChar: mark,
    minWordLength: 1,
    html: false,
  });

  const points = [];
  let letters = 0;
  for (const symbol of hyphenators[language](word)) {
    if (symbol === mark) {
      points.push(letters);
    } else {
      letters++;
    }
  }

  const kept = points.filter((point) => point >= left && point <= word.length - right);
  output += `${language}\t${word}\t${kept.join(",")}\n`;
}

fs.writeFileSync(expectedPath, output);
